-- ----------------------------
-- 供应链模块基础表 MySQL 脚本
-- 回滚顺序：
-- drop table if exists supply_org_cloud_tenant_bind;
-- drop table if exists supply_cloud_tenant;
-- drop table if exists supply_event_log;
-- drop table if exists supply_collect_log;
-- drop table if exists supply_event_subscription;
-- drop table if exists supply_collect_config;
-- drop table if exists supply_cloud_platform;
-- drop table if exists supply_physical_resource;
-- drop table if exists supply_supplier_user;
-- drop table if exists supply_supplier_platform_account;
-- drop table if exists supply_supplier;
-- ----------------------------

create table if not exists supply_supplier (
    id bigint not null comment '主键ID',
    tenant_id varchar(20) not null comment '租户编号',
    supplier_code varchar(64) not null comment '供应商编码',
    supplier_name varchar(64) not null comment '供应商名称',
    supplier_short_name varchar(64) default null comment '供应商简称',
    supplier_type varchar(32) not null comment '供应商类型',
    credit_code varchar(32) default null comment '统一社会信用代码',
    service_scope varchar(255) default null comment '服务范围',
    contact_name varchar(64) default null comment '联系人',
    contact_phone varchar(32) default null comment '联系电话',
    contact_email varchar(128) default null comment '联系邮箱',
    address varchar(255) default null comment '联系地址',
    cooperation_type varchar(32) default null comment '合作方式',
    status char(1) not null default '0' comment '状态（0启用 1停用）',
    onboard_time datetime default null comment '合作开始时间',
    offboard_time datetime default null comment '合作结束时间',
    remark varchar(500) default null comment '备注',
    create_dept bigint default null comment '创建部门',
    create_by bigint default null comment '创建人',
    create_time datetime default null comment '创建时间',
    update_by bigint default null comment '更新人',
    update_time datetime default null comment '更新时间',
    del_flag char(1) not null default '0' comment '删除标志（0存在 1删除）',
    primary key (id),
    unique key uk_supply_supplier_code (tenant_id, supplier_code, del_flag),
    unique key uk_supply_supplier_name (tenant_id, supplier_name, del_flag),
    unique key uk_supply_supplier_credit_code (tenant_id, credit_code, del_flag),
    key idx_supply_supplier_status (tenant_id, status)
) engine=innodb comment='供应商主数据';

create table if not exists supply_supplier_platform_account (
    id bigint not null comment '主键ID',
    tenant_id varchar(20) not null comment '租户编号',
    supplier_id bigint not null comment '供应商ID',
    cloud_platform_id bigint default null comment '云平台ID',
    account_name varchar(128) not null comment '账号名称',
    account_type varchar(32) default null comment '账号类型',
    account_identifier varchar(128) not null comment '账号标识',
    account_status char(1) not null default '0' comment '账号状态（0启用 1停用）',
    last_verified_time datetime default null comment '最近校验时间',
    remark varchar(500) default null comment '备注',
    create_dept bigint default null comment '创建部门',
    create_by bigint default null comment '创建人',
    create_time datetime default null comment '创建时间',
    update_by bigint default null comment '更新人',
    update_time datetime default null comment '更新时间',
    del_flag char(1) not null default '0' comment '删除标志（0存在 1删除）',
    primary key (id),
    key idx_supply_supplier_account_supplier (tenant_id, supplier_id),
    key idx_supply_supplier_account_platform (tenant_id, cloud_platform_id)
) engine=innodb comment='供应商平台账号';

create table if not exists supply_supplier_user (
    id bigint not null comment '主键ID',
    tenant_id varchar(20) not null comment '租户编号',
    supplier_id bigint not null comment '供应商ID',
    user_id bigint not null comment '系统用户ID',
    create_dept bigint default null comment '创建部门',
    create_by bigint default null comment '创建人',
    create_time datetime default null comment '创建时间',
    update_by bigint default null comment '更新人',
    update_time datetime default null comment '更新时间',
    del_flag char(1) not null default '0' comment '删除标志（0存在 1删除）',
    primary key (id),
    unique key uk_supply_supplier_user (tenant_id, user_id, del_flag)
) engine=innodb comment='供应商用户绑定';

create table if not exists supply_physical_resource (
    id bigint not null comment '主键ID',
    tenant_id varchar(20) not null comment '租户编号',
    resource_code varchar(64) not null comment '资源编号',
    supplier_id bigint not null comment '供应商ID',
    device_name varchar(128) not null comment '设备名称',
    device_type varchar(64) not null comment '设备类型',
    device_model varchar(128) default null comment '设备型号',
    serial_number varchar(128) not null comment '序列号',
    asset_tag varchar(64) default null comment '资产标签',
    resource_status varchar(32) not null comment '资源状态',
    rack_location varchar(128) default null comment '机柜位置',
    idc_location varchar(128) default null comment '机房位置',
    manage_ip varchar(64) default null comment '管理IP',
    purchase_date date default null comment '采购日期',
    expire_date date default null comment '到期日期',
    spec_payload json comment '规格扩展JSON',
    remark varchar(500) default null comment '备注',
    create_dept bigint default null comment '创建部门',
    create_by bigint default null comment '创建人',
    create_time datetime default null comment '创建时间',
    update_by bigint default null comment '更新人',
    update_time datetime default null comment '更新时间',
    del_flag char(1) not null default '0' comment '删除标志（0存在 1删除）',
    primary key (id),
    unique key uk_supply_physical_resource_code (tenant_id, resource_code, del_flag),
    unique key uk_supply_physical_resource_sn (tenant_id, serial_number, del_flag),
    key idx_supply_physical_resource_supplier (tenant_id, supplier_id),
    key idx_supply_physical_resource_type (tenant_id, device_type),
    key idx_supply_physical_resource_location (tenant_id, idc_location)
) engine=innodb comment='物理资源台账';

create table if not exists supply_cloud_platform (
    id bigint not null comment '主键ID',
    tenant_id varchar(20) not null comment '租户编号',
    platform_code varchar(64) not null comment '平台编码',
    platform_name varchar(128) not null comment '平台名称',
    platform_type varchar(64) not null comment '平台类型',
    provider_code varchar(64) not null comment '供应商编码',
    resource_pool_code varchar(64) default null comment '资源池编码',
    region_code varchar(64) default null comment '区域编码',
    access_url varchar(255) not null comment '接入地址',
    api_version varchar(32) default null comment 'API版本',
    description varchar(500) default null comment '平台描述',
    status char(1) not null default '0' comment '状态（0启用 1停用）',
    create_dept bigint default null comment '创建部门',
    create_by bigint default null comment '创建人',
    create_time datetime default null comment '创建时间',
    update_by bigint default null comment '更新人',
    update_time datetime default null comment '更新时间',
    del_flag char(1) not null default '0' comment '删除标志（0存在 1删除）',
    primary key (id),
    unique key uk_supply_cloud_platform_code (tenant_id, platform_code, del_flag),
    unique key uk_supply_cloud_platform_name (tenant_id, platform_name, del_flag),
    key idx_supply_cloud_platform_type (tenant_id, platform_type),
    key idx_supply_cloud_platform_pool (tenant_id, resource_pool_code)
) engine=innodb comment='云平台主数据';

create table if not exists supply_collect_config (
    id bigint not null comment '主键ID',
    tenant_id varchar(20) not null comment '租户编号',
    cloud_platform_id bigint not null comment '云平台ID',
    provider_code varchar(64) not null comment '供应商编码',
    collect_url varchar(255) not null comment '采集地址',
    sync_endpoint varchar(255) default null comment '同步回调地址',
    collect_scope varchar(32) not null comment '采集范围',
    collect_mode varchar(32) not null comment '采集模式',
    sync_strategy varchar(32) not null comment '同步策略',
    connector_code varchar(64) not null comment '连接器编码',
    auth_type varchar(32) not null comment '认证类型',
    auth_payload text comment '认证载荷（加密存储）',
    scope_filter json comment '采集范围过滤JSON',
    collect_options json comment '采集选项JSON',
    execute_cycle varchar(32) not null comment '执行周期',
    timeout_seconds int not null default 30 comment '超时秒数',
    retry_times int not null default 0 comment '重试次数',
    verify_ssl tinyint(1) not null default 1 comment '是否校验SSL证书（1校验 0不校验）',
    status char(1) not null default '0' comment '状态（0启用 1停用）',
    last_collect_time datetime default null comment '最近采集时间',
    last_success_time datetime default null comment '最近成功时间',
    last_collect_status varchar(32) default null comment '最近采集状态',
    last_error_message varchar(500) default null comment '最近错误信息',
    next_collect_time datetime default null comment '下次采集时间',
    remark varchar(500) default null comment '备注',
    create_dept bigint default null comment '创建部门',
    create_by bigint default null comment '创建人',
    create_time datetime default null comment '创建时间',
    update_by bigint default null comment '更新人',
    update_time datetime default null comment '更新时间',
    del_flag char(1) not null default '0' comment '删除标志（0存在 1删除）',
    primary key (id),
    unique key uk_supply_collect_config_scope (tenant_id, cloud_platform_id, collect_scope, del_flag),
    key idx_supply_collect_config_status (tenant_id, status)
) engine=innodb comment='快照采集配置';

create table if not exists supply_event_subscription (
    id bigint not null comment '主键ID',
    tenant_id varchar(20) not null comment '租户编号',
    cloud_platform_id bigint not null comment '云平台ID',
    provider_code varchar(64) not null comment '供应商编码',
    event_scope varchar(32) not null comment '事件范围',
    ingest_mode varchar(32) not null comment '接入模式',
    topic_name varchar(128) default null comment '主题名称',
    consumer_group varchar(128) default null comment '消费组',
    endpoint_path varchar(255) default null comment 'Webhook接收路径',
    auth_type varchar(32) default null comment '鉴权类型',
    auth_payload text comment '鉴权载荷（加密存储）',
    data_format varchar(32) not null comment '数据格式',
    schema_version varchar(32) not null comment 'Schema版本',
    status char(1) not null default '0' comment '状态（0启用 1停用）',
    last_event_time datetime default null comment '最近事件时间',
    last_error_message varchar(500) default null comment '最近错误信息',
    remark varchar(500) default null comment '备注',
    create_dept bigint default null comment '创建部门',
    create_by bigint default null comment '创建人',
    create_time datetime default null comment '创建时间',
    update_by bigint default null comment '更新人',
    update_time datetime default null comment '更新时间',
    del_flag char(1) not null default '0' comment '删除标志（0存在 1删除）',
    primary key (id),
    unique key uk_supply_event_subscription_scope (tenant_id, cloud_platform_id, event_scope, del_flag),
    key idx_supply_event_subscription_status (tenant_id, status)
) engine=innodb comment='实时事件订阅配置';

create table if not exists supply_collect_log (
    id bigint not null comment '主键ID',
    tenant_id varchar(20) not null comment '租户编号',
    collect_config_id bigint not null comment '采集配置ID',
    cloud_platform_id bigint not null comment '云平台ID',
    collect_scope varchar(32) not null comment '采集范围',
    execute_mode varchar(32) not null comment '执行模式',
    job_instance_id varchar(128) default null comment '任务实例ID',
    trace_id varchar(128) default null comment '链路追踪ID',
    trigger_user_id bigint default null comment '触发用户ID',
    start_time datetime default null comment '开始时间',
    end_time datetime default null comment '结束时间',
    duration_ms bigint default null comment '耗时毫秒',
    result_status varchar(32) default null comment '执行结果状态',
    sync_status varchar(32) default null comment '同步状态',
    resource_count int default null comment '资源数量',
    cloud_tenant_count int default null comment '云租户数量',
    sync_record_count int default null comment '同步记录数量',
    config_snapshot json comment '配置快照JSON',
    error_message varchar(500) default null comment '错误信息',
    create_dept bigint default null comment '创建部门',
    create_by bigint default null comment '创建人',
    create_time datetime default null comment '创建时间',
    update_by bigint default null comment '更新人',
    update_time datetime default null comment '更新时间',
    del_flag char(1) not null default '0' comment '删除标志（0存在 1删除）',
    primary key (id),
    key idx_supply_collect_log_config (tenant_id, collect_config_id, start_time)
) engine=innodb comment='采集执行日志';

create table if not exists supply_event_log (
    id bigint not null comment '主键ID',
    tenant_id varchar(20) not null comment '租户编号',
    subscription_id bigint not null comment '订阅ID',
    cloud_platform_id bigint not null comment '云平台ID',
    event_scope varchar(32) not null comment '事件范围',
    event_key varchar(255) default null comment '事件业务键',
    source_event_id varchar(128) default null comment '源事件ID',
    event_time datetime default null comment '事件时间',
    ingest_time datetime default null comment '接收时间',
    process_status varchar(32) default null comment '处理状态',
    trace_id varchar(128) default null comment '链路追踪ID',
    raw_payload json comment '原始事件JSON',
    normalized_payload json comment '标准化事件JSON',
    error_message varchar(500) default null comment '错误信息',
    create_dept bigint default null comment '创建部门',
    create_by bigint default null comment '创建人',
    create_time datetime default null comment '创建时间',
    update_by bigint default null comment '更新人',
    update_time datetime default null comment '更新时间',
    del_flag char(1) not null default '0' comment '删除标志（0存在 1删除）',
    primary key (id),
    unique key uk_supply_event_source_id (tenant_id, subscription_id, source_event_id, del_flag),
    key idx_supply_event_key (tenant_id, event_scope, event_key),
    key idx_supply_event_time (tenant_id, event_time)
) engine=innodb comment='实时事件日志';

create table if not exists supply_cloud_tenant (
    id bigint not null comment '主键ID',
    tenant_id varchar(20) not null comment '租户编号',
    cloud_platform_id bigint not null comment '云平台ID',
    external_tenant_id varchar(128) not null comment '外部租户ID',
    external_parent_id varchar(128) default null comment '外部父租户ID',
    cloud_tenant_name varchar(128) not null comment '云租户名称',
    cloud_tenant_code varchar(128) default null comment '云租户编码',
    tenant_status varchar(32) default null comment '租户状态',
    region_code varchar(64) default null comment '区域编码',
    source_account_identifier varchar(128) default null comment '来源账号标识',
    raw_payload json comment '原始数据JSON',
    last_sync_time datetime default null comment '最近同步时间',
    sync_status varchar(32) default null comment '同步状态',
    create_dept bigint default null comment '创建部门',
    create_by bigint default null comment '创建人',
    create_time datetime default null comment '创建时间',
    update_by bigint default null comment '更新人',
    update_time datetime default null comment '更新时间',
    del_flag char(1) not null default '0' comment '删除标志（0存在 1删除）',
    primary key (id),
    unique key uk_supply_cloud_tenant_external (tenant_id, cloud_platform_id, external_tenant_id, del_flag),
    key idx_supply_cloud_tenant_platform (tenant_id, cloud_platform_id)
) engine=innodb comment='云租户快照';

create table if not exists supply_org_cloud_tenant_bind (
    id bigint not null comment '主键ID',
    tenant_id varchar(20) not null comment '租户编号',
    org_id bigint not null comment '组织ID',
    cloud_platform_id bigint not null comment '云平台ID',
    cloud_tenant_snapshot_id bigint not null comment '云租户快照ID',
    bind_status varchar(32) not null comment '绑定状态',
    effective_time datetime default null comment '生效时间',
    invalid_time datetime default null comment '失效时间',
    binding_remark varchar(500) default null comment '绑定备注',
    create_dept bigint default null comment '创建部门',
    create_by bigint default null comment '创建人',
    create_time datetime default null comment '创建时间',
    update_by bigint default null comment '更新人',
    update_time datetime default null comment '更新时间',
    del_flag char(1) not null default '0' comment '删除标志（0存在 1删除）',
    primary key (id),
    unique key uk_supply_org_cloud_tenant (tenant_id, cloud_tenant_snapshot_id, del_flag)
) engine=innodb comment='组织与云租户绑定';
