# 安全配置
security:
  # 不校验白名单
  ignore:
    whites:
      - /auth/code
      - /auth/logout
      - /auth/login
      - /auth/binding/*
      - /auth/register
      - /auth/tenant/list
      - /resource/sms/code
      - /resource/sse/close
      - /*/v3/api-docs
      - /*/error
      - /csrf
      - /warm-flow-ui/**

spring:
  cloud:
    # 网关配置
    gateway:
      # 打印请求日志(自定义)
      requestLog: true
      server:
        webflux:
          discovery:
            locator:
              lowerCaseServiceId: true
              enabled: true
          routes:
            # 认证中心
            - id: csmp-auth
              uri: lb://csmp-auth
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            # 代码生成
            - id: csmp-gen
              uri: lb://csmp-gen
              predicates:
                - Path=/tool/**
              filters:
                - StripPrefix=1
            # 系统模块
            - id: csmp-system
              uri: lb://csmp-system
              predicates:
                - Path=/system/**,/monitor/**
              filters:
                - StripPrefix=1
            # 系统模块 API
            - id: csmp-system-api
              uri: lb://csmp-system
              predicates:
                - Path=/api/system/**
            # 资源服务
            - id: csmp-resource
              uri: lb://csmp-resource
              predicates:
                - Path=/resource/**
              filters:
                - StripPrefix=1
            # 资源服务 API
            - id: csmp-resource-api
              uri: lb://csmp-resource
              predicates:
                - Path=/api/resource/**
            # workflow服务
            - id: csmp-workflow
              uri: lb://csmp-workflow
              predicates:
                - Path=/workflow/**
              filters:
                - StripPrefix=1
            # workflow服务 API
            - id: csmp-workflow-api
              uri: lb://csmp-workflow
              predicates:
                - Path=/api/workflow/**
            # 供应链监管
            - id: csmp-supply
              uri: lb://csmp-supply
              predicates:
                - Path=/supply/**
              filters:
                - StripPrefix=1
            # 供应链监管兼容路由
            - id: csmp-supply-api-compat
              uri: lb://csmp-supply
              predicates:
                - Path=/api/supply/**
              filters:
                - StripPrefix=2
            # 定制化对接
            - id: csmp-adapter
              uri: lb://csmp-adapter
              predicates:
                - Path=/api/adapter/**
            # 费用账单
            - id: csmp-billing
              uri: lb://csmp-billing
              predicates:
                - Path=/api/billing/**
            # 运营管理
            - id: csmp-operation
              uri: lb://csmp-operation
              predicates:
                - Path=/api/operation/**
            # 风险管理
            - id: csmp-risk
              uri: lb://csmp-risk
              predicates:
                - Path=/api/risk/**
            # 资源监管
            - id: csmp-monitor-resource
              uri: lb://csmp-monitor-resource
              predicates:
                - Path=/api/monitor-resource/**
            # 业务监管
            - id: csmp-monitor-business
              uri: lb://csmp-monitor-business
              predicates:
                - Path=/api/monitor-business/**
            # warm-flow服务
            - id: warm-flow
              uri: lb://csmp-workflow
              predicates:
                - Path=/warm-flow-ui/**,/warm-flow/**
            # 演示服务
            - id: csmp-demo
              uri: lb://csmp-demo
              predicates:
                - Path=/demo/**
              filters:
                - StripPrefix=1
            # MQ演示服务
            - id: csmp-test-mq
              uri: lb://csmp-test-mq
              predicates:
                - Path=/test-mq/**
              filters:
                - StripPrefix=1
